algorytm:
    path: /ktory/alg/zastosowac
    controller: App\Controller\KtoryAlgZastosowacController::index
hello_page:
  path: /
  controller: App\Controller\HelloPageController::index

dodanie_do_bazy:
  path: /article/admin
  controller: App\Controller\ArticleAdminContorller::index

usuniecia_artykulu:
  path: /article/delete/{id}
  controller: App\Controller\ArticleAdminContorller::delete

usuniecia_godz_ucz:
  path: /article/delete/dni/uczelni/{id}
  controller: App\Controller\ArticleAdminContorller::delete_uczelnie

usuniecia_teachers:
  path: /article/delete/teachers/{id}
  controller: App\Controller\ArticleAdminContorller::delete_teachers

sort_algorithms:
  path: /sort/algorithms
  controller: App\Controller\SortAlgorithmsController::index

bubble_sort:
  path: /bubble/sort
  controller: App\Controller\BubbleSortController::index
quick_sort:
  path: /quick/sort
  controller: App\Controller\QuickSortController::index
counting_sort:
  path: /counting/sort
  controller: App\Controller\CountingSortController::index

merge_sort:
  path: /merge/sort
  controller: App\Controller\MergeSortController::index

heap_sort:
  path: /heap/sort
  controller: App\Controller\HeapSortController::index


test:
  path: /test
  controller: App\Controller\TestController::index